repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.5
  hooks:
    - id: terraform_validate
      args:
      - --hook-config=--retry-once-with-cleanup=true
    - id: terraform_providers_lock
      args:
      - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
    - id: terraform_docs
      args:
        - --hook-config=--create-file-if-not-exist=true
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_trivy
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.4.2
  hooks:
  - id: sqlfluff-fix
    args: [--dialect, athena]
